### PR TITLE
Add indent plugin

### PR DESCRIPTION
**Pull request by tpope**
I thought this would be a quick-and-dirty first pass, but after I ironed out all the unacceptable false positives, it was more or less fully implemented. :shrug:

### CODE REVIEW

**Comment by kalekundert** [comment]
I'm still reading the code, but one thing I noticed is that when writing a multiline string, the leading `>` doesn't get added to new lines anymore.

**Comment by tpope** [comment]
That would be the change to `'comments'` in a prior commit. It can be brought back by adding `,b:>`.

**Comment by kalekundert** [comment]
Ah, ok.  I think I found another issue, though, which is that strings can be interpreted as dict keys.  For example, when I type out the following text, `baz` gets an extra indent because `bar:` is interpreted as a dict key:
```
foo:
  - bar:
    - baz
```
Possibly related, dict-key-looking strings also get mistakenly unindented when they follow a list item:
```
foo:
  - bar
- baz:
```

**Comment by tpope** [comment]
Good catch, fixed.

**Comment by tpope** [comment]
Just pushed another change where if you _change_ `'shiftwidth'` and re-indent the document, it'll try to avoid leaving behind orphans at the old `'shiftwidth'`. Noticed when testing your example. (Edit: this only works reliably when decreasing `'shiftwidth'`. I don't think a robust solution when increasing is possible. Not a big deal imo.)

**Comment by kalekundert** [comment]
Awesome, this is really nice.  Thanks for all the contributions!

**Pull request merged**
